export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  FORBIDDEN: 'FORBIDDEN',
  CSRF_INVALID: 'CSRF_INVALID',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  PHONE_NOT_SUPPORTED: 'PHONE_NOT_SUPPORTED',
  INVALID_CHAT_ID: 'INVALID_CHAT_ID',
  INVALID_MEDIA_TYPE: 'INVALID_MEDIA_TYPE',
  INVALID_MEDIA_URL: 'INVALID_MEDIA_URL',
  WHATSAPP_NOT_CONNECTED: 'WHATSAPP_NOT_CONNECTED',
  WAHA_UNAVAILABLE: 'WAHA_UNAVAILABLE',
  MESSAGE_SEND_FAILED: 'MESSAGE_SEND_FAILED',
  MEDIA_SEND_FAILED: 'MEDIA_SEND_FAILED',
  IMAGE_SEND_FAILED: 'IMAGE_SEND_FAILED',
  VIDEO_SEND_FAILED: 'VIDEO_SEND_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
