export enum SessionStatus {
  QR_REQUIRED = 'QR_REQUIRED',
  CONNECTING = 'CONNECTING',
  CONNECTED = 'CONNECTED',
  DISCONNECTED = 'DISCONNECTED',
  ERROR = 'ERROR',
}

export enum WhatsappAccountMode {
  SEND_ONLY = 'SEND_ONLY',
  MESSENGER = 'MESSENGER',
}

export enum IdempotencyScope {
  SEND = 'SEND',
  GROUP_CREATE = 'GROUP_CREATE',
  GROUP_ADD = 'GROUP_ADD',
  GROUP_RENAME = 'GROUP_RENAME',
  GROUP_REMOVE = 'GROUP_REMOVE',
  GROUP_LEAVE = 'GROUP_LEAVE',
}

export enum IdempotencyStatus {
  PROCESSING = 'PROCESSING',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
  OUTCOME_UNKNOWN = 'OUTCOME_UNKNOWN',
}
